#!/usr/bin/env node

/**
 * nix utility to open a chrome browser without control elements
 * without tabs, address bar etc
 *
 */

const input = process.argv[2]
if (typeof input === 'undefined') {
  console.log('provide URL to open as the first argument')
}

let urlHref;
try {
  urlHref = new URL(input).href
} catch {
  console.log('invalid URL')
  process.exit(1)
}

const { spawn } = require('child_process');
spawn('/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome', ['--new-window',  `--app=${urlHref}`])
process.exit(0)
