#!/usr/bin/env node

/**
 * Encode input to base64 string and output the result into standard output
 *
 */

let data = process.argv[2]
if (data === '-f') {
  const fs = require('fs')
  const path = require('path')
  const filePath = process.argv[3]
  if (!filePath || !filePath.length) {
    console.error('provide file path after -f flag, e64 -f path/to/file')
    process.exit(1)
  }
  try {
    data = fs.readFileSync(path.resolve(filePath))
  } catch (err) {
    console.error(`cannot read file \`${filePath}\``)
    process.exit(1)
  }
}

console.log(
  Buffer.from(data).toString('base64')
)
