#!/usr/bin/env node

/**
 * Unix time utilities
 *
 */

// convert unix epoch to datetime string
const ts = Number(process.argv[2])
if (isNaN(ts)) {
  console.log('invalid unix time')
  process.exit(1)
}

console.log(new Date(ts).toLocaleString('sg'))
